[package]
name = "todo_list"
version = "0.1.0"
authors = ["Fredrik Andersson <fredrik.andersson@widespace.com>, Clayton Marshall <marsha88@purdue.edu>"]

[dependencies]
rust_redux = { path = "../../"}
